auth/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from auth.views import (
    logout, ChangePasswordView, AjaxPasswordResetView,
    AjaxPasswordResetDoneView, CrmLoginView, CrmLoginByTokenView,
    BackToCrmView
)

urlpatterns = [
    path('logout/', logout, name="logout"),
    path('change-password/', login_required(ChangePasswordView.as_view()), name="change-password"),
    path('reset-password/', PasswordResetView.as_view(), name="reset_password"),
    path('reset-password-ajax/', AjaxPasswordResetView.as_view(), name="reset_password_ajax"),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset-password-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset-password-done-ajax/', AjaxPasswordResetDoneView.as_view(), name="password_reset_done_ajax"),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', CrmLoginView.as_view(), name="login"),
    path('login-from-crm/', csrf_exempt(CrmLoginByTokenView.as_view())),
    path('back-to-crm/', login_required(BackToCrmView.as_view()), name="back_to_crm"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from core.views.main import HomeView
from payments.views.instant_payment import InstantPayView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),

    path('api/', include('core.api.urls')),
    path('payments/', include('payments.urls')),
    path('accounts/', include("auth.urls")),

    path('instant-pay/', InstantPayView.as_view(), name='instant-pay'),

    path("i18n/", include("django.conf.urls.i18n")),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['core']), name='javascript-catalog'),
]

core/api/urls.py
from django.urls import path

from core.api.views.organization import CustomerCrmStatusUpdateAPIView
from core.api.views.test_drive import CreateTestDriveCustomerAPIView
from core.api.views.invoices import NewInvoicesAPIView

urlpatterns = [
    path('new_invoices/', NewInvoicesAPIView.as_view(), name='new_invoices'),
    path('test-drive/', CreateTestDriveCustomerAPIView.as_view(), name='test_drive_flow'),
    path('update-crm-status/', CustomerCrmStatusUpdateAPIView.as_view(), name='update_crm_status'),
]

core/urls.py
from django.urls import path

from . import views
from .views.dashboard import DashboardView

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    path('customers/fast-create/', views.CustomerFastCreateView.as_view(), name='customer-fast-create'),
    path('customers/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customers/<pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customers/<pk>/set-status/', views.CustomerUpdateStatusView.as_view(), name='customer-update-status'),
    path('customers/<pk>/edit/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customers/<pk>/integration/', views.CustomerCreateExternalIntegrationView.as_view(), name='customer-create-integration'),
    path('customers/<pk>/activate/', views.CustomerActivateFormView.as_view(), name='customer-activate'),
    path('customers/<pk>/lock/', views.CustomerLockAccessView.as_view(), name='customer-lock-crm'),
    path('customers/<pk>/delete-crm/', views.CustomerDeleteCrmView.as_view(), name='customer-delete-crm'),

    path('archived-customers/', views.ArchivedCustomerListView.as_view(), name='archived-customer-list'),
    path('archived-customers/<pk>/delete-customer/', views.DeleteCustomerView.as_view(), name='delete-customer'),

    path('invoices/', views.InvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<pk>/', views.InvoiceDetailView.as_view(), name='invoice-detail'),
    path('invoices/<pk>/pay/', views.InvoicePayView.as_view(), name='invoice-pay'),
    path('invoices/<int:invoice_pk>/items/create', views.InvoiceItemCreateView.as_view(), name='invoice-item-create'),
    path('invoices/<int:invoice_pk>/items/<int:pk>/edit', views.InvoiceItemUpdateView.as_view(), name='invoice-item-update'),

    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('customer/<pk>/licenses/create/', views.LicenseCreateView.as_view(), name='license-create'),
    path('customer/<pk>/invoices/create/', views.CustomerInvoiceCreateView.as_view(), name='invoice-create'),
    path('licenses/<pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('licenses/<pk>/edit/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('licenses/<pk>/prolong/', views.LicenseProlongView.as_view(), name='license-prolong'),

    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('transactions/<pk>/cancel/', views.TransactionCancelView.as_view(), name='transaction-cancel'),
]

core/forms/common.py
# Used to reduce boilerplate for disabled form fields
DISABLED = {'disabled': True, 'required': False}

core/forms/registration_forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _

from common.forms import CrmForm, CrmModelForm
from core.models import CustomerType, Customer


class CustomerRegistrationForm(CrmModelForm):
    contact_email = forms.EmailField(label='Email', required=True)
    agreement_accepted = forms.BooleanField(required=True)

    def save(self, commit=True):
        return super().save(commit)

    class Meta:
        model = Customer
        fields = ('name', 'type', 'contact_email', 'agreement_accepted')


class CustomerUserCreateForm(CrmForm):
    first_name = forms.CharField(label=_('Имя'))
    last_name = forms.CharField(label=_('Фамилия'))
    username = UsernameField(label=_('Имя пользователя'), widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=_("Пароль"), strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
        help_text=password_validation.password_validators_help_text_html()
    )
    confirm_password = forms.CharField(
        label=_("Повторите пароль"), strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('confirm_password'):
            self.add_error('password', _('Пароли не совпадают'))

        password_validation.validate_password(self.cleaned_data.get('confirm_password'))
        return self.cleaned_data

core/api/views/invoices.py
from datetime import timedelta

from django.utils import timezone
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.auth.token import ExternalCrmTokenAuthentication
from core.api.permissions.customer import IsCustomerPermission
from core.api.serializers.invoice import InvoiceSerializer
from core.models.choices import CustomerStatuses


class NewInvoicesAPIView(APIView):
    """ Used to retrieve autogenerated Invoices which is not paid.
        Data will be used to notify Customers by 3rd party service
    """

    serializer_class = InvoiceSerializer
    authentication_classes = [ExternalCrmTokenAuthentication]
    permission_classes = [IsAuthenticated, IsCustomerPermission]

    NOTIFY_EVERY_N_DAYS = 3

    def get(self, request, *args, **kwargs):
        data = InvoiceSerializer(self.get_queryset(), many=True).data
        return Response(status=200, data=data)

    def get_queryset(self):
        customer = self.request.user.customer
        if customer.status == CustomerStatuses.INACTIVE:
            return customer.invoices.none()

        n_days_ago = timezone.now() - timedelta(self.NOTIFY_EVERY_N_DAYS)
        invoice_ids = list(
            customer.invoices.filter(is_paid=False)
            .exclude(last_notified_at__gt=n_days_ago)
            .values_list("id", flat=True)
        )

        invoices = customer.invoices.filter(pk__in=invoice_ids)
        invoices.update(last_notified_at=timezone.now())

        return invoices

core/api/views/organization.py
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.auth.token import ExternalCrmTokenAuthentication
from core.constants import (
    INVALID_CUSTOMER_BY_TOKEN, INVALID_CUSTOMER_ORG_ID,
    CRM_STATUS_CHANGE_SUCCESS,CRM_INVALID_STATUS
)
from core.models.choices import CrmStatuses


class CustomerCrmStatusUpdateAPIView(APIView):
    authentication_classes = [ExternalCrmTokenAuthentication]
    permission_classes = []

    def post(self, request, *args, **kwargs):
        org_id = request.data.get('org_id')
        status = request.data.get('status')
        customer = request.user.customer

        if status not in CrmStatuses:
            return Response({'message': CRM_INVALID_STATUS}, status=400)

        if not customer:
            return Response({'message': INVALID_CUSTOMER_BY_TOKEN}, status=400)

        if not org_id == customer.org_id:
            return Response({'message': INVALID_CUSTOMER_ORG_ID}, status=400)

        customer.crm_status = status
        customer.save(update_fields=['crm_status'])
        return Response({'message': CRM_STATUS_CHANGE_SUCCESS}, status=200)

core/api/views/test_drive.py
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.permissions.auth import ExternalTokenAuthenticationPermission
from core.api.serializers.test_drive import TestDriveCustomerCreateSerializer
from core.constants import INVALID_CUSTOMER_DATA, CUSTOMER_CREATE_SUCCESS
from core.exceptions import BaseError
from core.services.test_drive import TestDriveFacadeService


class CreateTestDriveCustomerAPIView(APIView):
    permission_classes = [ExternalTokenAuthenticationPermission]
    authentication_classes = []

    def post(self, request, *args, **kwargs):
        serializer = TestDriveCustomerCreateSerializer(data=request.data)

        if not serializer.is_valid():
            return Response(
                status=400,
                data={
                    'message': INVALID_CUSTOMER_DATA,
                    'errors': serializer.errors
                }
            )

        try:
            accept_url = TestDriveFacadeService.perform_test_drive_integration(**serializer.validated_data)
            return Response(
                status=200,
                data={
                    'message': CUSTOMER_CREATE_SUCCESS,
                    'accept_url': accept_url
                }
            )

        except BaseError as e:
            return Response(status=400, data={'message': e.message})

core/views/dashboard.py
from django.utils import timezone

from common.views import SuperUserTemplateView
from core.services.dashboard import DashboardService
from core.services.mrr import MRRService


class DashboardView(SuperUserTemplateView):
    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        dashboard_info = DashboardService.get_dashboard_info()
        transactions_by_months = MRRService.get_transactions_by_months()
        paid_for_months = MRRService.get_paid_for_months()

        return {
            'transactions_by_months': transactions_by_months,
            'paid_for_months': paid_for_months,
            'test_drive_customers': dashboard_info.get('test_drive_customers'),
            'paid_customers': dashboard_info.get('paid_customers'),
            'need_to_pay_customers':  dashboard_info.get('need_to_pay_customers'),
            'late_customers': dashboard_info.get('late_customers'),
            'inactive_customers': dashboard_info.get('inactive_customers'),
            **super().get_context_data(**kwargs)
        }


class MRRView(SuperUserTemplateView):
    template_name = 'core/mrr.html'

    def get_context_data(self, **kwargs):
        customers, paid_for_months = MRRService.get_monthly_payment_by_customers()
        current_month = timezone.now().date().replace(day=1)

        return {
            'customers': customers,
            'paid_for_months': paid_for_months,
            'current_month': current_month
        }

core/views/licenses.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from common.utils.date_utils import parse_date_type
from common.utils.parsing import get_int
from common.views import SuperUserTemplateView, SuperUserFormView, SuperUserRequiredView
from core import models, forms, exceptions
from core.choices import LicenseTypes
from core.services import InvoiceService
from core.services.license import LicenseCheckService


class LicenseListView(SuperUserTemplateView):
    template_name = 'core/licenses/list.html'

    def update_context(self, context):
        filters = self.get_filters()

        context['filters'] = filters
        context['has_filters'] = any(filters.values())

        context['customers'] = models.Customer.objects.only('id', 'name')
        context['license_entities'] = models.LicenseEntity.objects.only('id', 'name')
        context['licenses'] = models.License.objects.get_filtered_licenses(**filters).exclude(customer__status='archived')

    def get_filters(self):
        return {
            'license_entity': get_int(self.request.GET.get('license_entity')),
            'customer': get_int(self.request.GET.get('customer')),
            'start_date': parse_date_type(self.request.GET.get('start_date')),
            'end_date': parse_date_type(self.request.GET.get('end_date')),
        }


class LicenseDetailView(SuperUserTemplateView):
    template_name = 'core/licenses/detail.html'

    def update_context(self, context):
        license = get_object_or_404(models.License, pk=self.kwargs.get('pk'))
        invoice_ids = set(models.LicenseInvoiceItem.objects.filter(license=license).values_list('invoice_id', flat=True))

        context['license'] = license
        context['invoices'] = models.Invoice.objects.filter(pk__in=invoice_ids)


class LicenseCreateView(SuperUserFormView):
    template_name = 'core/licenses/create.html'
    form_class = forms.LicenseCreateForm

    def get_object(self):
        customer_id = self.kwargs["pk"]
        return get_object_or_404(models.Customer, pk=customer_id)

    def get_initial(self):
        start_date = timezone.now()
        end_date = start_date + timezone.timedelta(days=6)

        return {
            'customer': self.get_object(),
            'license_entity': models.LicenseEntity.objects.first(),
            'type': LicenseTypes.MONTHLY,
            'start_date': start_date,
            'end_date': end_date,
            **super().get_initial(),
        }

    def get_context_data(self, **kwargs):
        return {
            'customer': self.get_object(),
            **super().get_context_data(**kwargs)
        }

    def form_valid(self, form):
        form.save()
        LicenseCheckService.check_license_and_update_crm_for(form.instance.customer)
        return self.redirect()

    def redirect(self):
        customer_id = self.request.GET.get('customer')
        if customer_id:
            return redirect(reverse('customer-detail', kwargs={'pk': customer_id}))

        return redirect(reverse('license-list'))


class LicenseUpdateView(SuperUserFormView):
    template_name = 'core/licenses/create.html'
    form_class = forms.LicenseCreateForm

    def get_context_data(self, **kwargs):
        license_ = self.get_object()

        return {
            'customer': license_.customer,
            **super().get_context_data(**kwargs)
        }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()

        return kwargs

    def form_valid(self, form):
        form.save()
        LicenseCheckService.check_license_and_update_crm_for(form.instance.customer)
        return self.redirect()

    def redirect(self):
        license_id = self.request.GET.get('license')
        if license_id:
            return redirect(reverse('license-detail', kwargs={'pk': license_id}))

        customer_id = self.request.GET.get('customer')
        if customer_id:
            return redirect(reverse('customer-detail', kwargs={'pk': customer_id}))

        return redirect(reverse('license-list'))

    def get_object(self):
        return get_object_or_404(models.License, pk=self.kwargs.get('pk'))


class LicenseProlongView(SuperUserRequiredView):
    def post(self, request, *args, **kwargs):
        license = get_object_or_404(models.License, pk=self.kwargs.get('pk'))
        try:
            invoice = InvoiceService.create_new_for_license(license)
            LicenseCheckService.check_license_and_update_crm_for(license.customer)
            messages.success(request, _('Лицензия успешно продлена'))
            return redirect(reverse('invoice-detail', kwargs={'pk': invoice.id}))

        except exceptions.LicensePeriodIntersectionError as e:
            messages.error(request, e.message)
            return redirect(reverse('license-detail', kwargs={'pk': license.id}))

core/templates/core/customer/registration.html
{% extends 'base.html' %}
{% load i18n %}
{% block body %}
    {% get_current_language as LANGUAGE_CODE %}

    <div class="container is-fluid">
        <div class="modal-block form-box">
            <form method="post" class="item non-hover" action="{% url 'set_language' %}" style="margin-top: 10px;">
                {% csrf_token %}
                <button class="non-button language-switch {% if LANGUAGE_CODE == 'en' %}selected{% endif %}" type="submit" name="language"
                        value="en">English
                </button>
                <button class="non-button language-switch {% if LANGUAGE_CODE == 'ru' %}selected{% endif %}" type="submit" name="language"
                        value="ru">Русский
                </button>
                <button class="non-button language-switch {% if LANGUAGE_CODE == 'ky' %}selected{% endif %}" type="submit" name="language"
                        value="ky">Кыргызча
                </button>

            </form>
            <div class="modal-title">{% trans 'Регистрация в Billing CRM' %}</div>
            <form class="crm-form" method="post">
                {% csrf_token %}
                {{ form.name.label_tag }}
                {{ form.name }}
                {{ form.name.errors }}

                {{ form.type.label_tag }}
                <div class="select">
                    {{ form.type }}
                </div>
                {{ form.type.errors }}

                {{ form.contact_email.label_tag }}
                {{ form.contact_email }}
                {{ form.contact_email.errors }}

                <label for="id_agreement_accepted">
                    {% trans 'Согласен с условиями использования' %}
                    <a href="{% url 'agreement' %}" target="_blank">{% trans 'Ознакомиться' %}</a>
                </label>
                {{ form.agreement_accepted }}
                {{ form.agreement_accepted.errors }}

                <div style="display: flex; margin-top: 20px; justify-content: space-between;">
                    <button class="crm-button info" type="submit">
                        {% trans 'Зарегистрироваться' %}
                    </button>

                    <a href="{% url 'login' %}"  class="crm-button ">
                        {% trans 'Войти' %}
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/customer/registration_success.html
{% extends 'core/../base.html' %}
{% load i18n %}
{% block body %}
    <div class="container is-fluid">
        <div class="modal-block form-box">
            <div style="text-align: center; margin-bottom: 20px">
                <div class="modal-title">{% trans 'Настройка завершена' %}</div>
                <p>{% trans 'Мы провели начальную настройку системы для вас' %}.</p>
                <p>{% trans 'Нажмите на кнопку ниже чтобы начать путешествие' %}!</p>
            </div>
            <form id="admin-personal-account-form"
                  style="display: flex; justify-content: center; align-content: center;"
                  action="{{ integration.crm_url }}/accounts/admin-login/"
                  method="post" class="item">
                <input type="hidden" name="token" value="{{ integration.value }}">
                <button type="submit" class="crm-button">{% trans 'Перейти' %}</button>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/customer/set_password.html
{% extends 'core/../base.html' %}
{% load i18n %}
{% block body %}
    <div class="container is-fluid">
        <div class="modal-block form-box">
            <div class="modal-title">{% trans 'Создание пользователя' %}</div>
            <p>{% trans 'Благодарим за регистрацию' %}!</p>
            <p>{% trans 'Для того чтобы начать работу, вам необходимо создать учетную запись.' %}</p>

            <form class="crm-form" method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                <div class="columns">
                    <div class="column">
                        {{ form.first_name.label_tag }}
                        {{ form.first_name }}
                        {{ form.first_name.errors }}
                    </div>
                    <div class="column">
                        {{ form.last_name.label_tag }}
                        {{ form.last_name }}
                        {{ form.last_name.errors }}
                    </div>
                </div>

                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.errors }}

                <div class="columns">
                    <div class="column">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>
                    <div class="column">
                        {{ form.confirm_password.label_tag }}
                        {{ form.confirm_password }}
                        {{ form.confirm_password.errors }}
                    </div>
                </div>

                <div style="margin-top: 20px;">
                    <button  type="submit" class="crm-button">
                        {% trans 'Создать' %}
                    </button>
                </div>
            </form>

        </div>
    </div>
{% endblock %}