auth/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from auth.views import (
    logout, ChangePasswordView, AjaxPasswordResetView,
    AjaxPasswordResetDoneView, CrmLoginView, CrmLoginByTokenView,
    BackToCrmView
)

urlpatterns = [
    path('logout/', logout, name="logout"),
    path('change-password/', login_required(ChangePasswordView.as_view()), name="change-password"),
    path('reset-password/', PasswordResetView.as_view(), name="reset_password"),
    path('reset-password-ajax/', AjaxPasswordResetView.as_view(), name="reset_password_ajax"),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset-password-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset-password-done-ajax/', AjaxPasswordResetDoneView.as_view(), name="password_reset_done_ajax"),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', CrmLoginView.as_view(), name="login"),
    path('login-from-crm/', csrf_exempt(CrmLoginByTokenView.as_view())),
    path('back-to-crm/', login_required(BackToCrmView.as_view()), name="back_to_crm"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from core.views.main import HomeView
from payments.views.instant_payment import InstantPayView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),

    path('api/', include('core.api.urls')),
    path('payments/', include('payments.urls')),
    path('accounts/', include("auth.urls")),

    path('instant-pay/', InstantPayView.as_view(), name='instant-pay'),

    path("i18n/", include("django.conf.urls.i18n")),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['core']), name='javascript-catalog'),
]

core/api/urls.py
from django.urls import path

from core.api.views.organization import CustomerCrmStatusUpdateAPIView
from core.api.views.test_drive import CreateTestDriveCustomerAPIView
from core.api.views.invoices import NewInvoicesAPIView

urlpatterns = [
    path('new_invoices/', NewInvoicesAPIView.as_view(), name='new_invoices'),
    path('test-drive/', CreateTestDriveCustomerAPIView.as_view(), name='test_drive_flow'),
    path('update-crm-status/', CustomerCrmStatusUpdateAPIView.as_view(), name='update_crm_status'),
]

core/urls.py
from django.urls import path

from . import views
from .views.dashboard import DashboardView

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    path('customers/fast-create/', views.CustomerFastCreateView.as_view(), name='customer-fast-create'),
    path('customers/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customers/<pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customers/<pk>/set-status/', views.CustomerUpdateStatusView.as_view(), name='customer-update-status'),
    path('customers/<pk>/edit/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customers/<pk>/integration/', views.CustomerCreateExternalIntegrationView.as_view(), name='customer-create-integration'),
    path('customers/<pk>/activate/', views.CustomerActivateFormView.as_view(), name='customer-activate'),
    path('customers/<pk>/lock/', views.CustomerLockAccessView.as_view(), name='customer-lock-crm'),
    path('customers/<pk>/delete-crm/', views.CustomerDeleteCrmView.as_view(), name='customer-delete-crm'),

    path('archived-customers/', views.ArchivedCustomerListView.as_view(), name='archived-customer-list'),
    path('archived-customers/<pk>/delete-customer/', views.DeleteCustomerView.as_view(), name='delete-customer'),

    path('invoices/', views.InvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<pk>/', views.InvoiceDetailView.as_view(), name='invoice-detail'),
    path('invoices/<pk>/pay/', views.InvoicePayView.as_view(), name='invoice-pay'),
    path('invoices/<int:invoice_pk>/items/create', views.InvoiceItemCreateView.as_view(), name='invoice-item-create'),
    path('invoices/<int:invoice_pk>/items/<int:pk>/edit', views.InvoiceItemUpdateView.as_view(), name='invoice-item-update'),

    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('customer/<pk>/licenses/create/', views.LicenseCreateView.as_view(), name='license-create'),
    path('customer/<pk>/invoices/create/', views.CustomerInvoiceCreateView.as_view(), name='invoice-create'),
    path('licenses/<pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('licenses/<pk>/edit/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('licenses/<pk>/prolong/', views.LicenseProlongView.as_view(), name='license-prolong'),

    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('transactions/<pk>/cancel/', views.TransactionCancelView.as_view(), name='transaction-cancel'),
]

core/models/customer.py
from ckeditor.fields import RichTextField
from django.db import models
from django.db.models import SET_NULL
from django.utils.translation import gettext_lazy as _

from common.models import TimestampedModel, NULLABLE
from . import CustomUser, CrmServer
from .choices import CustomerStatuses, OrgTypesEnum, CrmStatuses

status_choices, default_status = CustomerStatuses.choices, CustomerStatuses.INACTIVE
crm_status_choices, default_crm_status = CrmStatuses.choices, CrmStatuses.UNKNOWN


class Customer(TimestampedModel):
    type = models.ForeignKey('CustomerType', SET_NULL, verbose_name=_('Тип CRM'), null=True, blank=False)
    assignees = models.ManyToManyField(CustomUser, 'assigned_customers', verbose_name=_('Ответственные'))
    created_by = models.ForeignKey(CustomUser, SET_NULL, 'created_customers', **NULLABLE, verbose_name=_('Кем добавлен'))

    status = models.CharField(max_length=50, choices=status_choices, verbose_name=_('Статус'), default=default_status)

    name = models.CharField(max_length=255, verbose_name=_('Название организации'))
    description = RichTextField(verbose_name=_('Описание'), **NULLABLE)
    url = models.URLField(verbose_name=_('Сайт компании'), **NULLABLE)

    server = models.ForeignKey(CrmServer, on_delete=SET_NULL, related_name='customers', **NULLABLE)
    org_id = models.IntegerField(verbose_name=_("ID Организации на сервере"), **NULLABLE)

    crm_status = models.CharField(verbose_name='CRM Status', choices=crm_status_choices, default=default_crm_status, max_length=20)
    users_count = models.PositiveSmallIntegerField(verbose_name=_('Масштаб компании/Кол-во пользователей'))

    contact_phone_number = models.CharField(max_length=255, verbose_name=_('Номер телефона'), **NULLABLE)
    contact_person = models.CharField(max_length=255, verbose_name=_('Контактное лицо'), **NULLABLE)
    contact_skype = models.CharField(max_length=255, verbose_name='Skype', **NULLABLE)
    contact_email = models.EmailField(verbose_name=_('Почта'), **NULLABLE)

    def __str__(self):
        return self.name

    def get_current_license(self):
        return self.licenses.order_by('-end_date').first()

    def has_crm_integration(self):
        user = self.accounts.first()
        return hasattr(user, 'x_integration')

    def get_crm_integration(self):
        user = self.accounts.first()
        return getattr(user, 'x_integration', None)

    def remove_server(self):
        self.server = None
        self.save()

    class Meta:
        verbose_name = _('Клиент')
        verbose_name_plural = _('Клиенты')
        default_related_name = 'customers'


class CustomerType(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Название'))
    code = models.CharField(max_length=100, choices=OrgTypesEnum.choices, verbose_name=_('Внутренний код'), null=True, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Тип клиента')
        verbose_name_plural = _('Типы клиентов')

core/models/invoice.py
from base64 import b64encode, b64decode
from contextlib import suppress
from typing import Optional

from ckeditor.fields import RichTextField
from django.db import models, transaction
from django.db.models import signals
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from polymorphic.models import PolymorphicModel

from common.models import TimestampedModel, NULLABLE
from . import Customer, License
from .. import exceptions
from ..managers.invoice import InvoiceManager


class Invoice(TimestampedModel):
    objects = InvoiceManager()

    customer = models.ForeignKey(to=Customer, on_delete=models.PROTECT, related_name='invoices', verbose_name=_('Клиент'))

    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))
    initial_amount = models.DecimalField(verbose_name=_('Сумма без учета скидки $'), max_digits=15, decimal_places=2, default=0)
    discount_amount = models.DecimalField(verbose_name=_('Сумма скидки $'), max_digits=15, decimal_places=2, default=0)
    final_amount = models.DecimalField(verbose_name=_('Итоговая сумма $'), max_digits=15, decimal_places=2, default=0)
    is_paid = models.BooleanField(default=False, verbose_name=_('Оплачено?'))
    payment_date = models.DateTimeField(verbose_name=_('Дата оплаты'), **NULLABLE)
    last_notified_at = models.DateTimeField(verbose_name=_("Последнее напоминание"), **NULLABLE)

    def __str__(self):
        return f"{self.customer}-{self.title}: {self.final_amount} $"

    @property
    def slug(self):
        decoded_slug = b64encode(f"inv:{self.id}".encode("utf-8")).decode("utf-8")
        decoded_slug = decoded_slug.replace("=", "_")
        return decoded_slug

    @staticmethod
    def parse_slug(slug_encoded) -> Optional[int]:
        """
        returns invoice id
        """
        try:
            slug_encoded = slug_encoded.replace("_", "=")
            slug = b64decode(slug_encoded.encode("utf-8")).decode("utf-8")
            if slug.startswith("inv:"):
                return int(slug[4:])
        except:
            pass

    @transaction.atomic
    def save(self, **kwargs):
        self.initial_amount = self.initial_amount or 0
        self.discount_amount = self.discount_amount or 0

        if self.discount_amount > self.initial_amount:
            raise exceptions.InvalidDiscountAmountError()

        self.final_amount = self.initial_amount - self.discount_amount

        super().save(**kwargs)

    def recalculate_amount(self):
        total_initial_amount = total_discount_amount = total_final_amount = 0

        for item in self.items.all():
            total_initial_amount += item.initial_amount
            total_discount_amount += item.discount_amount
            total_final_amount += item.final_amount

        self.initial_amount = total_initial_amount
        self.discount_amount = total_discount_amount
        self.final_amount = total_final_amount

        self.save()

    def mark_as_paid(self, payment_date=None):
        self.is_paid = True
        self.payment_date = payment_date or timezone.now()
        self.save()

    def mark_as_unpaid(self):
        self.is_paid = False
        self.payment_date = None
        self.save()

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _('Счет на оплату')
        verbose_name_plural = _('Счета на оплату')


@receiver(signals.post_save, sender=Invoice)
def prolong_licences_if_needed(sender, instance, **kwargs):
    if instance.is_paid:
        for item in instance.items.instance_of(LicenseInvoiceItem):
            with suppress(exceptions.InvalidLicenseDateError):
                item.license.prolong_license(item.end_date)


class InvoiceItem(PolymorphicModel):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items', verbose_name=_('Счет на оплату'))

    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))
    initial_amount = models.DecimalField(verbose_name=_('Сумма без учета скидки $'), max_digits=15, decimal_places=2)
    discount_amount = models.DecimalField(verbose_name=_('Сумма скидки $'), max_digits=15, decimal_places=2)
    final_amount = models.DecimalField(verbose_name=_('Итоговая сумма $'), max_digits=15, decimal_places=2)
    description = RichTextField(verbose_name=_('Описание'), **NULLABLE)

    def __str__(self):
        return f"{self.invoice} > {self.title}"

    def save(self, *args, **kwargs):
        if self.discount_amount > self.initial_amount:
            raise exceptions.InvalidDiscountAmountError()

        self.final_amount = self.initial_amount - self.discount_amount
        super().save(**kwargs)

    class Meta:
        verbose_name = _('Обьект счета на оплату')
        verbose_name_plural = _('Обьекты счета на оплату')


@receiver(signals.post_save, sender=InvoiceItem)
@receiver(signals.post_delete, sender=InvoiceItem)
def recalculate_invoice_amount(sender, instance, **kwargs):
    instance.invoice.recalculate_amount()


class LicenseInvoiceItem(InvoiceItem):
    license = models.ForeignKey(to=License, on_delete=models.PROTECT, related_name='invoice_items', verbose_name=_('Лицензия'))

    start_date = models.DateField(verbose_name=_('Начало периода'))
    end_date = models.DateField(verbose_name=_('Конец периода'))

    def __str__(self):
        return f"{self.invoice} > {self.license}"

    class Meta:
        verbose_name = _('Обьект счета на оплату: Лицензия')
        verbose_name_plural = _('Обьекты счета на оплату: Лицензия')


# Propagate signal across all children of a polymorphic parent.
# This code should be after declaring all of InvoiceItem children
for subclass in InvoiceItem.__subclasses__():
    signals.post_save.connect(recalculate_invoice_amount, sender=subclass)
    signals.post_delete.connect(recalculate_invoice_amount, sender=subclass)

core/models/license.py
from datetime import date

from ckeditor.fields import RichTextField
from dateutil.relativedelta import relativedelta
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from common.models import TimestampedModel, NULLABLE
from . import Customer
from .. import exceptions, managers
from ..choices import LicenseTypes


class License(TimestampedModel):
    objects = managers.LicenseManager()

    customer = models.ForeignKey(to=Customer, on_delete=models.PROTECT, verbose_name=_('Клиент'), related_name="licenses")
    license_entity = models.ForeignKey(to='LicenseEntity', on_delete=models.PROTECT, verbose_name=_('Лицензия за'))

    type = models.CharField(verbose_name=_('Тип'), choices=LicenseTypes.choices, max_length=50)
    start_date = models.DateField(verbose_name=_('Дата начала'))
    end_date = models.DateField(verbose_name=_('Дата окончания'))
    price = models.DecimalField(verbose_name=_('Цена $'), max_digits=10, decimal_places=2)
    discount_percentage = models.PositiveSmallIntegerField(verbose_name=_('Скидка %'), default=0)
    description = RichTextField(verbose_name=_('Описание'), **NULLABLE)
    active = models.BooleanField(verbose_name=_("Активен"), default=True)

    @property
    def title(self):
        return self.license_entity.name

    @property
    def days_left(self):
        return (self.end_date - timezone.now().date()).days

    @property
    def length(self):
        if self.type == LicenseTypes.MONTHLY:
            return relativedelta(months=1)

        elif self.type == LicenseTypes.ANNUAL:
            return relativedelta(years=1)

        elif self.type == LicenseTypes.TESTING:
            return relativedelta(days=14)

    def __str__(self):
        return f'{self.customer} - {self.license_entity}: {self.start_date} - {self.end_date}'

    def save(self, **kwargs):
        if self.does_overlap_other():
            raise exceptions.LicensePeriodIntersectionError()

        return super().save(**kwargs)

    def does_overlap_other(self):
        return License.objects.overlapping_licenses(self.customer, self.license_entity, self.start_date, self.end_date, self.pk).exists()

    def prolong_license(self, new_date: date):
        if new_date < self.end_date:
            raise exceptions.InvalidLicenseDateError()

        if License.objects.overlapping_licenses(self.customer, self.license_entity, self.start_date, new_date, self.pk).exists():
            raise exceptions.LicensePeriodIntersectionError()

        self.end_date = new_date
        self.save()

    class Meta:
        verbose_name = _('Лицензия')
        verbose_name_plural = _('Лицензии')
        default_related_name = 'licenses'


class LicenseEntity(TimestampedModel):
    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = RichTextField(**NULLABLE, verbose_name=_('Описание'))

    def __str__(self):
        return self.name

    @staticmethod
    def get_default():
        return LicenseEntity.objects.get_or_create(name='CRM')[0]

    class Meta:
        verbose_name = _('Объект лицензирования')
        verbose_name_plural = _('Объекты лицензирования')

core/forms/common.py
# Used to reduce boilerplate for disabled form fields
DISABLED = {'disabled': True, 'required': False}

core/templates/core/licenses/create.html
{% extends 'core/base.html' %}
{% load static extra_tags i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'libs/fastselect/fastselect.min.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'libs/fastselect/fastselect.standalone.min.js' %}"></script>

    <script>
        $(document).ready(function () {

            $("#id_start_date,#id_end_date").datepicker({
                dateFormat: "{{ JS_PICKER_DATE_FORMAT }}",
                firstDay: 1
            });
            $("#id_start_date,#id_end_date").attr("autocomplete", "off");

            $('#id_customer,#id_license_entity,#id_type').fastselect();
        })
    </script>
{% endblock %}

{% block content %}
    <div id="page-id">licenses</div>
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'customer-list' %}">{% trans 'Клиенты' %}</a></li>
            <li><a href="{% url 'customer-detail' customer.id %}" aria-current="page">{{ customer }}</a></li>
            <li><a href="{% url 'license-list' %}">{% trans 'Лицензии' %}</a></li>
            {% if form.instance.id %}
                <li><a href="{% url 'license-detail' form.instance.id %}" aria-current="page">{{ form.instance }}</a></li>
                <li class="is-active"><a href="#" aria-current="page">{% trans 'Редактировать' %}</a></li>
            {% else %}
                <li class="is-active"><a href="#" aria-current="page">{% trans 'Добавить' %}</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="modal-block" style="width: 444px;">
        {% if form.instance.id %}
            <div class="modal-title">{% trans 'Редактировать' %}</div>
        {% else %}
            <div class="modal-title">{% trans 'Новая лицензия' %}</div>
        {% endif %}
        <form method="post" enctype="multipart/form-data" class="crm-form">
            {% csrf_token %}

           {{ form.non_field_errors }}

            <div style="border-bottom: 1px solid rgba(169, 169, 169, 0.79)">
                {{ form.customer.label_tag }}
                {{ form.customer }}
                {{ form.customer.errors }}
            </div>
            <div style="border-bottom: 1px solid rgba(169, 169, 169, 0.79)">
                {{ form.license_entity.label_tag }}
                {{ form.license_entity }}
                {{ form.license_entity.errors }}
            </div>
            <div style="border-bottom: 1px solid rgba(169, 169, 169, 0.79)">
                {{ form.type.label_tag }}
                {{ form.type }}
                {{ form.type.errors }}
            </div>
            {{ form.start_date.label_tag }}
            {{ form.start_date }}
            {{ form.start_date.errors }}

            {{ form.end_date.label_tag }}
            {{ form.end_date }}
            {{ form.end_date.errors }}

            {{ form.price.label_tag }}
            {{ form.price }}
            {{ form.price.errors }}

            {{ form.discount_percentage.label_tag }}
            {{ form.discount_percentage }}
            {{ form.discount_percentage.errors }}

            {{ form.description.label_tag }}
            {{ form.description }}
            {{ form.description.errors }}

            {{ form.active.label_tag }}
            {{ form.active }}
            {{ form.active.errors }}

            {{ form.contact_skype.label_tag }}
            {{ form.contact_skype }}
            {{ form.contact_skype.errors }}


            <div class="separator"></div>
            <div class="bottom-buttons">
                <button type="submit" class="crm-button">
                    {% trans 'Сохранить' %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/core/licenses/list.html
{% extends 'core/base.html' %}

{% load static i18n extra_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'libs/fastselect/fastselect.min.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'libs/fastselect/fastselect.standalone.min.js' %}"></script>

    <script>
        $(document).ready(function () {

            $("#id_start_date,#id_end_date").datepicker({
                dateFormat: "{{ JS_PICKER_DATE_FORMAT }}",
                firstDay: 1
            });
            $("#id_start_date,#id_end_date").attr("autocomplete", "off");

            $('#id_customer,#id_license_entity').fastselect();
        })
    </script>
{% endblock %}

{% block content %}
    <div id="page-id">licenses</div>
    <div class="page-title">{% trans 'Лицензии' %}</div>
    <div>
        <form class="labeled page-toolbar">
            <div>
                <div class="label">{% trans 'Клиент' %}</div>
                <select name="customer" id="id_customer">
                    <option value="">---------</option>
                    {% for customer in customers %}
                        <option value="{{ customer.id }}" {% if filters|get:'customer' == customer.id %}selected{% endif %}>
                            {{ customer.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <div class="label">{% trans 'Лицензия за' %}</div>
                <select name="license_entity" id="id_license_entity">
                    <option value="">---------</option>
                    {% for entity in license_entities %}
                        <option value="{{ entity.id }}" {% if filters|get:'license_entity' == entity.id %}selected{% endif %}>
                            {{ entity.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label for="id_start_date" class="label">{% trans 'Дата начала' %}</label>
                <div class="control">
                    <div class="field">
                        <input class="input"
                               name="start_date" id="id_start_date"
                               value="{{ filters|get:'start_date'|default:'' }}"/>
                    </div>
                </div>
            </div>
            <div>
                <label for="id_end_date" class="label">{% trans 'Дата конца' %}</label>
                <div class="control">
                    <div class="field">
                        <input class="input"
                               placeholder=""
                               name="end_date" id="id_end_date"
                               value="{{ filters|get:'end_date'|default:'' }}"/>
                    </div>
                </div>
            </div>

            <div>
                <button class="button is-white" aria-haspopup="true" aria-controls="dropdown-menu2">
                        <span class="icon is-small">
                            <i class="fas fa-filter"></i>
                        </span>
                    <span>{% trans 'Фильтр' %}</span>
                </button>
            </div>
            {% if has_filters %}
                <div>
                    <a href="{% url 'license-list' %}" class="button is-danger">
                            <span class="icon is-small">
                               <i class="fas fa-times"></i>
                            </span>
                        <span>{% trans 'Очистить' %}</span>
                    </a>
                </div>
            {% endif %}
        </form>
    </div>

    <div class="subsection">
        <div class="subcontent">
            <table class="crm-table is-small">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{% trans 'Клиент' %}</th>
                    <th>{% trans 'Лицензия за' %}</th>
                    <th>{% trans 'Тип' %}</th>
                    <th>{% trans 'Дата начала' %}</th>
                    <th>{% trans 'Дата окончания' %}</th>
                    <th>{% trans 'Сумма' %}$</th>
                    <th>{% trans 'Скидка' %}%</th>
                    <th>{% trans 'Активна' %}</th>
                    <th>{% trans 'Действия' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for license in licenses|paginate:request %}
                    <tr id="invoice-item-{{ license.id }}" class="clickable link news-row" data-id="{{ license.id }}">
                        <td><a href="{% url 'license-detail' license.id %}">#{{ license.id }}</a></td>
                        <td>{{ license.customer }}</td>
                        <td>{{ license.license_entity }}</td>
                        <td>{{ license.get_type_display }}</td>
                        <td>{{ license.start_date|date:"d M Y" }}</td>
                        <td>{{ license.end_date|date:"d M Y" }}</td>
                        <td>${{ license.price|to_int }}</td>
                        <td>{{ license.discount_percentage }}%</td>
                        <td>
                            {% if license.active %}
                                <span class="icon active"><i class="fas fa-check-circle"></i></span>
                            {% else %}
                                <span class="icon inactive"><i class="fas fa-times-circle"></i></span>
                            {% endif %}
                        </td>
                        <td>
                            <a class="button is-small" href="{% url 'license-update' license.id %}?customer={{ license.customer_id }}">
                                {% trans 'Изменить' %}
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="100%">{% trans 'Лицензий нет' %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% pages licenses request filters %}
        </div>
    </div>
{% endblock %}