auth/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from auth.views import (
    logout, ChangePasswordView, AjaxPasswordResetView,
    AjaxPasswordResetDoneView, CrmLoginView, CrmLoginByTokenView,
    BackToCrmView
)

urlpatterns = [
    path('logout/', logout, name="logout"),
    path('change-password/', login_required(ChangePasswordView.as_view()), name="change-password"),
    path('reset-password/', PasswordResetView.as_view(), name="reset_password"),
    path('reset-password-ajax/', AjaxPasswordResetView.as_view(), name="reset_password_ajax"),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset-password-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset-password-done-ajax/', AjaxPasswordResetDoneView.as_view(), name="password_reset_done_ajax"),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', CrmLoginView.as_view(), name="login"),
    path('login-from-crm/', csrf_exempt(CrmLoginByTokenView.as_view())),
    path('back-to-crm/', login_required(BackToCrmView.as_view()), name="back_to_crm"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from core.views.main import HomeView
from payments.views.instant_payment import InstantPayView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),

    path('api/', include('core.api.urls')),
    path('payments/', include('payments.urls')),
    path('accounts/', include("auth.urls")),

    path('instant-pay/', InstantPayView.as_view(), name='instant-pay'),

    path("i18n/", include("django.conf.urls.i18n")),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['core']), name='javascript-catalog'),
]

core/api/urls.py
from django.urls import path

from core.api.views.organization import CustomerCrmStatusUpdateAPIView
from core.api.views.test_drive import CreateTestDriveCustomerAPIView
from core.api.views.invoices import NewInvoicesAPIView

urlpatterns = [
    path('new_invoices/', NewInvoicesAPIView.as_view(), name='new_invoices'),
    path('test-drive/', CreateTestDriveCustomerAPIView.as_view(), name='test_drive_flow'),
    path('update-crm-status/', CustomerCrmStatusUpdateAPIView.as_view(), name='update_crm_status'),
]

core/urls.py
from django.urls import path

from . import views
from .views.dashboard import DashboardView

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    path('customers/fast-create/', views.CustomerFastCreateView.as_view(), name='customer-fast-create'),
    path('customers/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customers/<pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customers/<pk>/set-status/', views.CustomerUpdateStatusView.as_view(), name='customer-update-status'),
    path('customers/<pk>/edit/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customers/<pk>/integration/', views.CustomerCreateExternalIntegrationView.as_view(), name='customer-create-integration'),
    path('customers/<pk>/activate/', views.CustomerActivateFormView.as_view(), name='customer-activate'),
    path('customers/<pk>/lock/', views.CustomerLockAccessView.as_view(), name='customer-lock-crm'),
    path('customers/<pk>/delete-crm/', views.CustomerDeleteCrmView.as_view(), name='customer-delete-crm'),

    path('archived-customers/', views.ArchivedCustomerListView.as_view(), name='archived-customer-list'),
    path('archived-customers/<pk>/delete-customer/', views.DeleteCustomerView.as_view(), name='delete-customer'),

    path('invoices/', views.InvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<pk>/', views.InvoiceDetailView.as_view(), name='invoice-detail'),
    path('invoices/<pk>/pay/', views.InvoicePayView.as_view(), name='invoice-pay'),
    path('invoices/<int:invoice_pk>/items/create', views.InvoiceItemCreateView.as_view(), name='invoice-item-create'),
    path('invoices/<int:invoice_pk>/items/<int:pk>/edit', views.InvoiceItemUpdateView.as_view(), name='invoice-item-update'),

    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('customer/<pk>/licenses/create/', views.LicenseCreateView.as_view(), name='license-create'),
    path('customer/<pk>/invoices/create/', views.CustomerInvoiceCreateView.as_view(), name='invoice-create'),
    path('licenses/<pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('licenses/<pk>/edit/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('licenses/<pk>/prolong/', views.LicenseProlongView.as_view(), name='license-prolong'),

    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('transactions/<pk>/cancel/', views.TransactionCancelView.as_view(), name='transaction-cancel'),
]

core/models/choices.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomerStatuses(models.TextChoices):
    TEST_DRIVE = 'test_drive', _('Тестовый период')
    INACTIVE = 'inactive', _('Неактивный')
    ACTIVE = 'active', _('Активный')
    ARCHIVED = 'archived', _('Архив')


class OrgTypesEnum(models.TextChoices):
    COURSES = "courses", _("Курсы")
    CORPORATE_COURSES = "corporate_courses", _("Корпоративные курсы")
    CRM = "crm", _("Универсальный CRM")


class CrmStatuses(models.TextChoices):
    UNKNOWN = 'unknown', _('Неизвестен')
    ACTIVE = 'active', _('Активно')
    LOCKED = 'locked', _('Заблокировано')
    DELETED = 'deleted', _('Удалено')

core/models/invoice.py
from base64 import b64encode, b64decode
from contextlib import suppress
from typing import Optional

from ckeditor.fields import RichTextField
from django.db import models, transaction
from django.db.models import signals
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from polymorphic.models import PolymorphicModel

from common.models import TimestampedModel, NULLABLE
from . import Customer, License
from .. import exceptions
from ..managers.invoice import InvoiceManager


class Invoice(TimestampedModel):
    objects = InvoiceManager()

    customer = models.ForeignKey(to=Customer, on_delete=models.PROTECT, related_name='invoices', verbose_name=_('Клиент'))

    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))
    initial_amount = models.DecimalField(verbose_name=_('Сумма без учета скидки $'), max_digits=15, decimal_places=2, default=0)
    discount_amount = models.DecimalField(verbose_name=_('Сумма скидки $'), max_digits=15, decimal_places=2, default=0)
    final_amount = models.DecimalField(verbose_name=_('Итоговая сумма $'), max_digits=15, decimal_places=2, default=0)
    is_paid = models.BooleanField(default=False, verbose_name=_('Оплачено?'))
    payment_date = models.DateTimeField(verbose_name=_('Дата оплаты'), **NULLABLE)
    last_notified_at = models.DateTimeField(verbose_name=_("Последнее напоминание"), **NULLABLE)

    def __str__(self):
        return f"{self.customer}-{self.title}: {self.final_amount} $"

    @property
    def slug(self):
        decoded_slug = b64encode(f"inv:{self.id}".encode("utf-8")).decode("utf-8")
        decoded_slug = decoded_slug.replace("=", "_")
        return decoded_slug

    @staticmethod
    def parse_slug(slug_encoded) -> Optional[int]:
        """
        returns invoice id
        """
        try:
            slug_encoded = slug_encoded.replace("_", "=")
            slug = b64decode(slug_encoded.encode("utf-8")).decode("utf-8")
            if slug.startswith("inv:"):
                return int(slug[4:])
        except:
            pass

    @transaction.atomic
    def save(self, **kwargs):
        self.initial_amount = self.initial_amount or 0
        self.discount_amount = self.discount_amount or 0

        if self.discount_amount > self.initial_amount:
            raise exceptions.InvalidDiscountAmountError()

        self.final_amount = self.initial_amount - self.discount_amount

        super().save(**kwargs)

    def recalculate_amount(self):
        total_initial_amount = total_discount_amount = total_final_amount = 0

        for item in self.items.all():
            total_initial_amount += item.initial_amount
            total_discount_amount += item.discount_amount
            total_final_amount += item.final_amount

        self.initial_amount = total_initial_amount
        self.discount_amount = total_discount_amount
        self.final_amount = total_final_amount

        self.save()

    def mark_as_paid(self, payment_date=None):
        self.is_paid = True
        self.payment_date = payment_date or timezone.now()
        self.save()

    def mark_as_unpaid(self):
        self.is_paid = False
        self.payment_date = None
        self.save()

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _('Счет на оплату')
        verbose_name_plural = _('Счета на оплату')


@receiver(signals.post_save, sender=Invoice)
def prolong_licences_if_needed(sender, instance, **kwargs):
    if instance.is_paid:
        for item in instance.items.instance_of(LicenseInvoiceItem):
            with suppress(exceptions.InvalidLicenseDateError):
                item.license.prolong_license(item.end_date)


class InvoiceItem(PolymorphicModel):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items', verbose_name=_('Счет на оплату'))

    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))
    initial_amount = models.DecimalField(verbose_name=_('Сумма без учета скидки $'), max_digits=15, decimal_places=2)
    discount_amount = models.DecimalField(verbose_name=_('Сумма скидки $'), max_digits=15, decimal_places=2)
    final_amount = models.DecimalField(verbose_name=_('Итоговая сумма $'), max_digits=15, decimal_places=2)
    description = RichTextField(verbose_name=_('Описание'), **NULLABLE)

    def __str__(self):
        return f"{self.invoice} > {self.title}"

    def save(self, *args, **kwargs):
        if self.discount_amount > self.initial_amount:
            raise exceptions.InvalidDiscountAmountError()

        self.final_amount = self.initial_amount - self.discount_amount
        super().save(**kwargs)

    class Meta:
        verbose_name = _('Обьект счета на оплату')
        verbose_name_plural = _('Обьекты счета на оплату')


@receiver(signals.post_save, sender=InvoiceItem)
@receiver(signals.post_delete, sender=InvoiceItem)
def recalculate_invoice_amount(sender, instance, **kwargs):
    instance.invoice.recalculate_amount()


class LicenseInvoiceItem(InvoiceItem):
    license = models.ForeignKey(to=License, on_delete=models.PROTECT, related_name='invoice_items', verbose_name=_('Лицензия'))

    start_date = models.DateField(verbose_name=_('Начало периода'))
    end_date = models.DateField(verbose_name=_('Конец периода'))

    def __str__(self):
        return f"{self.invoice} > {self.license}"

    class Meta:
        verbose_name = _('Обьект счета на оплату: Лицензия')
        verbose_name_plural = _('Обьекты счета на оплату: Лицензия')


# Propagate signal across all children of a polymorphic parent.
# This code should be after declaring all of InvoiceItem children
for subclass in InvoiceItem.__subclasses__():
    signals.post_save.connect(recalculate_invoice_amount, sender=subclass)
    signals.post_delete.connect(recalculate_invoice_amount, sender=subclass)

core/forms/common.py
# Used to reduce boilerplate for disabled form fields
DISABLED = {'disabled': True, 'required': False}

core/api/views/invoices.py
from datetime import timedelta

from django.utils import timezone
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.auth.token import ExternalCrmTokenAuthentication
from core.api.permissions.customer import IsCustomerPermission
from core.api.serializers.invoice import InvoiceSerializer
from core.models.choices import CustomerStatuses


class NewInvoicesAPIView(APIView):
    """ Used to retrieve autogenerated Invoices which is not paid.
        Data will be used to notify Customers by 3rd party service
    """

    serializer_class = InvoiceSerializer
    authentication_classes = [ExternalCrmTokenAuthentication]
    permission_classes = [IsAuthenticated, IsCustomerPermission]

    NOTIFY_EVERY_N_DAYS = 3

    def get(self, request, *args, **kwargs):
        data = InvoiceSerializer(self.get_queryset(), many=True).data
        return Response(status=200, data=data)

    def get_queryset(self):
        customer = self.request.user.customer
        if customer.status == CustomerStatuses.INACTIVE:
            return customer.invoices.none()

        n_days_ago = timezone.now() - timedelta(self.NOTIFY_EVERY_N_DAYS)
        invoice_ids = list(
            customer.invoices.filter(is_paid=False)
            .exclude(last_notified_at__gt=n_days_ago)
            .values_list("id", flat=True)
        )

        invoices = customer.invoices.filter(pk__in=invoice_ids)
        invoices.update(last_notified_at=timezone.now())

        return invoices

core/api/views/organization.py
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.auth.token import ExternalCrmTokenAuthentication
from core.constants import (
    INVALID_CUSTOMER_BY_TOKEN, INVALID_CUSTOMER_ORG_ID,
    CRM_STATUS_CHANGE_SUCCESS,CRM_INVALID_STATUS
)
from core.models.choices import CrmStatuses


class CustomerCrmStatusUpdateAPIView(APIView):
    authentication_classes = [ExternalCrmTokenAuthentication]
    permission_classes = []

    def post(self, request, *args, **kwargs):
        org_id = request.data.get('org_id')
        status = request.data.get('status')
        customer = request.user.customer

        if status not in CrmStatuses:
            return Response({'message': CRM_INVALID_STATUS}, status=400)

        if not customer:
            return Response({'message': INVALID_CUSTOMER_BY_TOKEN}, status=400)

        if not org_id == customer.org_id:
            return Response({'message': INVALID_CUSTOMER_ORG_ID}, status=400)

        customer.crm_status = status
        customer.save(update_fields=['crm_status'])
        return Response({'message': CRM_STATUS_CHANGE_SUCCESS}, status=200)

core/api/views/test_drive.py
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api.permissions.auth import ExternalTokenAuthenticationPermission
from core.api.serializers.test_drive import TestDriveCustomerCreateSerializer
from core.constants import INVALID_CUSTOMER_DATA, CUSTOMER_CREATE_SUCCESS
from core.exceptions import BaseError
from core.services.test_drive import TestDriveFacadeService


class CreateTestDriveCustomerAPIView(APIView):
    permission_classes = [ExternalTokenAuthenticationPermission]
    authentication_classes = []

    def post(self, request, *args, **kwargs):
        serializer = TestDriveCustomerCreateSerializer(data=request.data)

        if not serializer.is_valid():
            return Response(
                status=400,
                data={
                    'message': INVALID_CUSTOMER_DATA,
                    'errors': serializer.errors
                }
            )

        try:
            accept_url = TestDriveFacadeService.perform_test_drive_integration(**serializer.validated_data)
            return Response(
                status=200,
                data={
                    'message': CUSTOMER_CREATE_SUCCESS,
                    'accept_url': accept_url
                }
            )

        except BaseError as e:
            return Response(status=400, data={'message': e.message})

core/views/dashboard.py
from django.utils import timezone

from common.views import SuperUserTemplateView
from core.services.dashboard import DashboardService
from core.services.mrr import MRRService


class DashboardView(SuperUserTemplateView):
    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        dashboard_info = DashboardService.get_dashboard_info()
        transactions_by_months = MRRService.get_transactions_by_months()
        paid_for_months = MRRService.get_paid_for_months()

        return {
            'transactions_by_months': transactions_by_months,
            'paid_for_months': paid_for_months,
            'test_drive_customers': dashboard_info.get('test_drive_customers'),
            'paid_customers': dashboard_info.get('paid_customers'),
            'need_to_pay_customers':  dashboard_info.get('need_to_pay_customers'),
            'late_customers': dashboard_info.get('late_customers'),
            'inactive_customers': dashboard_info.get('inactive_customers'),
            **super().get_context_data(**kwargs)
        }


class MRRView(SuperUserTemplateView):
    template_name = 'core/mrr.html'

    def get_context_data(self, **kwargs):
        customers, paid_for_months = MRRService.get_monthly_payment_by_customers()
        current_month = timezone.now().date().replace(day=1)

        return {
            'customers': customers,
            'paid_for_months': paid_for_months,
            'current_month': current_month
        }

core/templates/core/invoices/create.html
{% extends 'core/base.html' %}
{% load static extra_tags i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'libs/fastselect/fastselect.min.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'libs/fastselect/fastselect.standalone.min.js' %}"></script>

    <script>
        $(document).ready(function () {

            $("#id_start_date,#id_end_date").datepicker({
                dateFormat: "{{ JS_PICKER_DATE_FORMAT }}",
                firstDay: 1
            });
            $("#id_start_date,#id_end_date").attr("autocomplete", "off");

            $('#id_license').fastselect();
        })
    </script>
{% endblock %}

{% block content %}
    <div id="page-id">customers</div>
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'customer-list' %}">{% trans 'Клиенты' %}</a></li>
            <li><a href="{% url 'customer-detail' customer.id %}" aria-current="page">{{ customer }}</a></li>
            <li><a href="{% url 'license-list' %}">{% trans 'Лицензии' %}</a></li>
            <li class="is-active"><a href="#" aria-current="page">{% trans 'Добавить' %}</a></li>
        </ul>
    </nav>
    <div class="modal-block" style="width: 444px;">
        <div class="modal-title">{% trans 'Новый счет' %}</div>
        <form method="post" enctype="multipart/form-data" class="crm-form">
            {% csrf_token %}

            {{ form.non_field_errors }}
            {{ form.media }}

            {{ form.license.label_tag }}
            {{ form.license }}
            {{ form.license.errors }}

            {{ form.start_date.label_tag }}
            {{ form.start_date }}
            {{ form.start_date.errors }}

            {{ form.end_date.label_tag }}
            {{ form.end_date }}
            {{ form.end_date.errors }}

            {{ form.initial_amount.label_tag }}
            {{ form.initial_amount }}
            {{ form.initial_amount.errors }}

            {{ form.discount_amount.label_tag }}
            {{ form.discount_amount }}
            {{ form.discount_amount.errors }}

            {{ form.description.label_tag }}
            {{ form.description }}
            {{ form.description.errors }}

            <div class="separator"></div>
            <div class="bottom-buttons">
                <button type="submit" class="crm-button">
                    {% trans 'Сохранить' %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/core/invoices/item-update.html
{% extends 'core/base.html' %}
{% load static extra_tags i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'libs/fastselect/fastselect.min.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'libs/fastselect/fastselect.standalone.min.js' %}"></script>

    <script>
        $(document).ready(function () {

            $("#id_start_date,#id_end_date").datepicker({
                dateFormat: "{{ JS_PICKER_DATE_FORMAT }}",
                firstDay: 1
            });
            $("#id_start_date,#id_end_date").attr("autocomplete", "off");

            $('#id_license').fastselect();
        })
    </script>
{% endblock %}

{% block content %}
    <div id="page-id">customers</div>
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'customer-list' %}">{% trans 'Клиенты' %}</a></li>
            <li><a href="{% url 'customer-detail' invoice.customer_id %}">{{ invoice.customer }}</a></li>
            <li><a href="{% url 'invoice-detail' invoice.id %}" aria-current="page">{{ invoice }}</a></li>
            {% if form.instance.id %}
                <li class="is-active"><a href="#" aria-current="page">{% trans 'Редактировать' %}</a></li>
            {% else %}
                <li class="is-active"><a href="#" aria-current="page">{% trans 'Новый объект счета' %}</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="modal-block" style="width: 444px;">
        {% if form.instance.id %}
            <div class="modal-title">{% trans 'Редактировать' %}</div>
        {% else %}
            <div class="modal-title">{% trans 'Новый объект счета' %}</div>
        {% endif %}
        <form method="post" enctype="multipart/form-data" class="crm-form">
            {% csrf_token %}
            {{ form }}
            <div class="separator"></div>
            <div class="bottom-buttons">
                <button type="submit" class="crm-button">
                    {% trans 'Сохранить' %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/core/invoices/list.html
{% extends 'core/base.html' %}

{% load static i18n extra_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'libs/fastselect/fastselect.min.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'libs/fastselect/fastselect.standalone.min.js' %}"></script>

    <script>
        $(document).ready(function () {

            $("#id_start_date,#id_end_date").datepicker({
                dateFormat: "{{ JS_PICKER_DATE_FORMAT }}",
                firstDay: 1
            });
            $("#id_start_date,#id_end_date").attr("autocomplete", "off");

            $('#id_customer,#id_invoice_entity').fastselect();
        })
    </script>
{% endblock %}

{% block content %}
    <div id="page-id">invoices</div>
    <div class="page-title">{% trans 'Счета на оплату' %}</div>
    <div>
        <form class="labeled page-toolbar">
            <div>
                <div class="label">{% trans 'Клиент' %}</div>
                <select name="customer" id="id_customer">
                    <option value="">---------</option>
                    {% for customer in customers %}
                        <option value="{{ customer.id }}" {% if filters|get:'customer' == customer.id %}selected{% endif %}>
                            {{ customer.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label for="id_start_date" class="label">{% trans 'Дата начала' %}</label>
                <div class="control">
                    <div class="field">
                        <input class="input"
                               name="start_date" id="id_start_date"
                               value="{{ filters|get:'start_date'|default:'' }}"/>
                    </div>
                </div>
            </div>
            <div>
                <label for="id_end_date" class="label">{% trans 'Дата конца' %}</label>
                <div class="control">
                    <div class="field">
                        <input class="input"
                               placeholder=""
                               name="end_date" id="id_end_date"
                               value="{{ filters|get:'end_date'|default:'' }}"/>
                    </div>
                </div>
            </div>


            <div>
                <div class="control has-icons-right">
                    <input name="search" class="input is-white" type="text"
                           placeholder="{% trans 'Поиск' %}"
                           value="{{ filters|get:'search'|default:'' }}">
                    <span class="icon is-small is-right"><i class="fas fa-search"></i></span>
                </div>
            </div>

            <div>
                <button class="button is-white" aria-haspopup="true" aria-controls="dropdown-menu2">
                        <span class="icon is-small">
                            <i class="fas fa-filter"></i>
                        </span>
                    <span>{% trans 'Фильтр' %}</span>
                </button>
            </div>
            {% if has_filters %}
                <div>
                    <a href="{% url 'invoice-list' %}" class="button is-danger">
                            <span class="icon is-small">
                               <i class="fas fa-times"></i>
                            </span>
                        <span>{% trans 'Очистить' %}</span>
                    </a>
                </div>
            {% endif %}
        </form>
    </div>

    <div class="subsection">
        <div class="subcontent">
            <table class="crm-table is-small is-small">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{% trans 'Клиент' %}</th>
                    <th>{% trans 'Название' %}</th>
                    <th>{% trans 'Изначальная сумма' %}</th>
                    <th>{% trans 'Сумма скидки' %}</th>
                    <th>{% trans 'Итоговая сумма' %}</th>
                    <th>{% trans 'Оплачен?' %}</th>
                    <th>{% trans 'Дата оплаты' %}</th>
                    <th>{% trans 'Действия' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for invoice in invoices|paginate:request %}
                    <tr class="clickable link">
                        <td>
                            <a href="{% url 'invoice-detail' invoice.id %}">#{{ invoice.id }}</a>
                        </td>
                        <td>{{ invoice.customer }}</td>
                        <td>{{ invoice.title }}</td>
                        <td>$ {{ invoice.initial_amount }}</td>
                        <td>$ {{ invoice.discount_amount }}</td>
                        <td>$ {{ invoice.final_amount }}</td>
                        <td>
                            {% if invoice.is_paid %}
                                <span class="icon active"><i class="fas fa-check-circle"></i></span>
                            {% else %}
                                <span class="icon inactive"><i class="fas fa-times-circle"></i></span>
                            {% endif %}
                        </td>
                        <td>{{ invoice.payment_date|default:'-' }}</td>
                        <td>
                            {% if not invoice.is_paid %}
                                <a class="button is-small" href="{% url 'invoice-pay' invoice.id %}">
                                    {% trans 'Внести оплату' %}
                                </a>
                            {% else %}
                                <button class="button is-small" disabled>
                                    {% trans 'Внести оплату' %}
                                </button>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="100%">{% trans 'Счетов нет' %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% pages invoices request filters %}
        </div>
    </div>
{% endblock %}